import { FieldAuditReport, GdprDataSubject, Soc2Control } from '../types/compliance';

export const SEED_FIELD_AUDITS: FieldAuditReport[] = [
  {
    id: 'audit-field-01',
    tenantId: 'tenant-danone-global',
    supplierId: 'sup-danone-02',
    supplierName: 'Agrícola Andina del Cacao S.A.C.',
    auditorName: 'Marc Vandevelde (Auditeur Senior Bureau Veritas)',
    auditDate: '2026-09-18T10:30:00Z',
    locationGps: '-8.18721, -76.51442 (Tocache, Pérou)',
    facilityType: 'FARM_COOPERATIVE',
    standardsAudited: ['FAIRTRADE', 'EUDR_DEFORESTATION', 'SA8000'],
    childLaborFreeVerified: true,
    safeWorkingConditionsVerified: true,
    fairWageVerified: true,
    environmentalComplianceScore: 94,
    evidencePhotosCount: 8,
    notes:
      'Visite sur site des parcelles agroforestières. Contrôle des registres de paie et entretiens individuels avec 14 planteurs. Aucun enfant présent sur les zones de récolte. Polygones GPS vérifiés conformes.',
    syncStatus: 'SYNCED_CLOUD',
    cryptoHash: 'sha256=fa772091bc88102a991044bb78921a4411ee880012bcfe891044bb78921a99',
  },
  {
    id: 'audit-field-02',
    tenantId: 'tenant-danone-global',
    supplierId: 'sup-danone-01',
    supplierName: 'BioLait Normandie SAS',
    auditorName: 'Camille Leroy (Inspecteur Qualité & RSE)',
    auditDate: '2026-09-22T14:15:00Z',
    locationGps: '49.18286, -0.37067 (Caen, France)',
    facilityType: 'FACTORY_MILL',
    standardsAudited: ['ECOCERT_BIO', 'ISO14001'],
    childLaborFreeVerified: true,
    safeWorkingConditionsVerified: true,
    fairWageVerified: true,
    environmentalComplianceScore: 98,
    evidencePhotosCount: 5,
    notes:
      'Audit de la cuverie et de la station d’épuration biologique. Conformité parfaite aux cahiers des charges Ecocert France.',
    syncStatus: 'SYNCED_CLOUD',
    cryptoHash: 'sha256=0198bb4577884102ef891044bb78921a4412ab78ef459900cde104781299bbec',
  },
];

export const SEED_GDPR_SUBJECTS: GdprDataSubject[] = [
  {
    id: 'gdpr-sub-01',
    tenantId: 'tenant-danone-global',
    fullName: 'Elena Rodriguez Mendoza',
    role: 'Directrice RSE & Certifications',
    company: 'Agrícola Andina del Cacao S.A.C.',
    email: 'elena.rodriguez@agricola-andina.pe',
    personalDataCategories: ['Nom & Prénom', 'Email Professionnel', 'Signature Électronique', 'Pièce d’identité auditeur'],
    legalBasis: 'CSRD_LEGAL_OBLIGATION',
    consentDate: '2024-03-12T09:00:00Z',
    retentionExpiryDate: '2034-12-31',
    status: 'ACTIVE',
    lastConsentVerifiedAt: '2026-03-10T11:00:00Z',
  },
  {
    id: 'gdpr-sub-02',
    tenantId: 'tenant-danone-global',
    fullName: 'Gérard Dupont',
    role: 'Directeur Général',
    company: 'BioLait Normandie SAS',
    email: 'gerard.dupont@biolait-normandie.fr',
    personalDataCategories: ['Nom & Prénom', 'Email Professionnel', 'Téléphone Direct'],
    legalBasis: 'CONTRACT_PERFORMANCE',
    consentDate: '2023-06-01T08:30:00Z',
    retentionExpiryDate: '2033-06-01',
    status: 'ACTIVE',
    lastConsentVerifiedAt: '2026-01-15T14:20:00Z',
  },
  {
    id: 'gdpr-sub-03',
    tenantId: 'tenant-danone-global',
    fullName: 'Ancien Contact Qualité (Fournisseur Radié)',
    role: 'Responsable Laboratoire',
    company: 'Ex-Fournisseur Arômes & Extraits',
    email: 'anonymized-user-8841@privacy.certiwatch.internal',
    personalDataCategories: ['Nom & Prénom (Anonymisés)', 'Email Haché'],
    legalBasis: 'EXPLICIT_CONSENT',
    consentDate: '2021-02-10T10:00:00Z',
    retentionExpiryDate: '2026-02-10',
    status: 'ANONYMIZED_RIGHT_TO_FORGET',
    lastConsentVerifiedAt: '2026-02-10T00:00:00Z',
    anonymizedAt: '2026-02-11T16:45:00Z',
    anonymizationProofHash: 'sha256=d41d8cd98f00b204e9800998ecf8427e000011448899aaeeff1234567890abcd',
  },
];

export const SEED_SOC2_CONTROLS: Soc2Control[] = [
  {
    id: 'soc2-01',
    category: 'SECURITY',
    controlId: 'CC6.1 - RBAC & Multi-Tenant',
    title: 'Contrôle d’Accès Basé sur les Rôles et Cloisonnement Strict des Tenants',
    description:
      'Chaque requête API et accès base de données est filtré par le tenantId cryptographiquement garanti. Aucun croisement de données inter-entreprises.',
    status: 'COMPLIANT',
    evidence: 'Isolation validée dans le store Redux/In-Memory et contrôle systématique de tenantId sur 100% des requêtes.',
    frequency: 'CONTINUOUS_AUTOMATED',
    lastAuditedAt: '2026-09-25T08:00:00Z',
  },
  {
    id: 'soc2-02',
    category: 'PROCESSING_INTEGRITY',
    controlId: 'CC6.6 - Immutable Audit Trail',
    title: 'Piste d’Audit Immuable avec Chaînage Cryptographique SHA-256',
    description:
      'Toute action (modification de certificat, dérogation ERP, purge RGPD) génère un bloc chaîné avec previousHash et signature SHA-256.',
    status: 'COMPLIANT',
    evidence: 'Vérificateur d’intégrité temps réel : 100% des blocs scellés et inviolables.',
    frequency: 'CONTINUOUS_AUTOMATED',
    lastAuditedAt: '2026-09-25T10:00:00Z',
  },
  {
    id: 'soc2-03',
    category: 'CONFIDENTIALITY',
    controlId: 'CC6.7 - Encryption at Rest & Transit',
    title: 'Chiffrement des Données Sensibles (AES-256 / TLS 1.3)',
    description:
      'Chiffrement systématique au repos des attestations d’audit et des secrets Webhooks. Protocole TLS 1.3 imposé pour les flux entrants et sortants.',
    status: 'COMPLIANT',
    evidence: 'Signature HMAC SHA-256 sur les webhooks et chiffrement fort des tokens API.',
    frequency: 'CONTINUOUS_AUTOMATED',
    lastAuditedAt: '2026-09-24T18:00:00Z',
  },
  {
    id: 'soc2-04',
    category: 'AVAILABILITY',
    controlId: 'A1.2 - Circuit Breaker & High Availability',
    title: 'Résilience face aux Pannes Registres & Protection contre le Déni de Service',
    description:
      'Circuit Breaker automatique avec bascule en mode cache 24h lors des indisponibilités des registres tiers (Ecocert, FSC, GOTS).',
    status: 'COMPLIANT',
    evidence: 'Seuil de 3 échecs consécutifs avant ouverture du circuit et reprise automatique avec backoff.',
    frequency: 'CONTINUOUS_AUTOMATED',
    lastAuditedAt: '2026-09-25T09:30:00Z',
  },
  {
    id: 'soc2-05',
    category: 'PRIVACY',
    controlId: 'P3.1 - RGPD Right to be Forgotten',
    title: 'Procédure Automatisée d’Anonymisation et Droit à l’Oubli (Art. 17 RGPD)',
    description:
      'Purge sécurisée des métadonnées nominatives avec émission d’une attestation d’anonymisation opposable sans rompre la piste d’audit comptable.',
    status: 'COMPLIANT',
    evidence: 'Module Droit à l’Oubli opérationnel avec hachage non réversible des emails et identités.',
    frequency: 'QUARTERLY',
    lastAuditedAt: '2026-09-20T14:00:00Z',
  },
];
