import { Tenant, User } from '../types/tenant';
import { Supplier } from '../types/supplier';
import { Certificate } from '../types/certificate';
import { ComplianceAlert } from '../types/alert';
import { AuditLogEntry } from '../types/audit';
import { ComplianceMatrixRule } from '../types/matrix';
import { CertificationProviderMetadata, OrchestrationConfig, OrchestratorRunLog } from '../types/connector';
import { EudrPlotDeclaration, GeneratedAuditPack } from '../types/report';

export const SEED_TENANTS: Tenant[] = [
  {
    id: 'tenant-danone-global',
    name: 'Danone Quality & Sourcing',
    slug: 'danone-sourcing',
    industry: 'AGRI_FOOD',
    monitoredCertificatesCount: 148,
    maxCertificatesAllowed: 2000,
    maxSuppliersAllowed: 500,
    tier: 'BUSINESS',
    pricePerCertMonthly: 2.2,
    createdAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'tenant-kering-luxury',
    name: 'Kering Group Supply Chain',
    slug: 'kering-supply',
    industry: 'LUXURY_TEXTILE',
    monitoredCertificatesCount: 890,
    maxCertificatesAllowed: 5000,
    maxSuppliersAllowed: 1200,
    tier: 'ENTERPRISE',
    pricePerCertMonthly: 1.85,
    createdAt: '2024-02-01T09:30:00Z',
  },
  {
    id: 'tenant-biocoop-france',
    name: 'Biocoop Distribution',
    slug: 'biocoop-france',
    industry: 'RETAIL',
    monitoredCertificatesCount: 215,
    maxCertificatesAllowed: 500,
    maxSuppliersAllowed: 150,
    tier: 'STARTER',
    pricePerCertMonthly: 2.8,
    createdAt: '2024-03-10T11:00:00Z',
  },
];

export const SEED_USERS: User[] = [
  {
    id: 'usr-admin-1',
    name: 'Claire de Montmirail',
    email: 'claire.demontmirail@danone-partner.com',
    role: 'ADMIN',
    department: 'Direction RSE & Compliance',
    tenantId: 'tenant-danone-global',
  },
  {
    id: 'usr-qm-1',
    name: 'Julien Lefebvre',
    email: 'julien.lefebvre@danone-partner.com',
    role: 'QUALITY_MANAGER',
    department: 'Assurance Qualité Matières Premières',
    tenantId: 'tenant-danone-global',
  },
  {
    id: 'usr-pm-1',
    name: 'Sarah Benali',
    email: 'sarah.benali@danone-partner.com',
    role: 'PROCUREMENT_MANAGER',
    department: 'Achats Directs Europe',
    tenantId: 'tenant-danone-global',
  },
  {
    id: 'usr-audit-1',
    name: 'Marc Vandevelde',
    email: 'marc.vandevelde@danone-partner.com',
    role: 'AUDITOR',
    department: 'Audit Interne & Conformité Tiers',
    tenantId: 'tenant-danone-global',
  },
  {
    id: 'usr-view-1',
    name: 'Léa Rossi',
    email: 'lea.rossi@danone-partner.com',
    role: 'VIEWER',
    department: 'Logistique & Approvisionnements',
    tenantId: 'tenant-danone-global',
  },
  // Kering user
  {
    id: 'usr-kering-1',
    name: 'Alexandre Dumas',
    email: 'alexandre.dumas@kering-group.com',
    role: 'ADMIN',
    department: 'Supply Chain Sustainable Materials',
    tenantId: 'tenant-kering-luxury',
  },
  // Biocoop user
  {
    id: 'usr-biocoop-1',
    name: 'Amélie Poulain',
    email: 'amelie.poulain@biocoop-reseau.fr',
    role: 'ADMIN',
    department: 'Filières Équitables & Bio',
    tenantId: 'tenant-biocoop-france',
  },
];

export const SEED_PROVIDERS: CertificationProviderMetadata[] = [
  {
    id: 'prov-ecocert',
    code: 'ECOCERT',
    name: 'Ecocert / Bio Certifications',
    standards: ['ECOCERT_BIO'],
    officialDomain: 'certificat.ecocert.com',
    publicSearchUrl: 'https://certificat.ecocert.com',
    apiAvailability: 'PUBLIC_REGISTRY_OPEN',
    rateLimitPolicy: 'Respecter 60 req/min, cache journalier requis par conditions',
    legalTermsSummary: 'Consultation autorisée pour vérification de conformité inter-entreprises.',
    status: 'OPERATIONAL',
    lastHealthCheck: '2026-09-24T06:45:00Z',
    avgResponseMs: 340,
    circuitBreakerState: 'CLOSED',
    consecutiveFailures: 0,
    monthlyRequestsCount: 1840,
    monthlyQuota: 10000,
    uptimePercentage: 99.9,
    ethicalScrapingPolicy: 'Respect strict du robots.txt, quota max 60 req/min, cache local 24h, aucun contournement de CAPTCHA',
    userAgentUsed: 'CertiWatch-Compliance-Bot/1.0 (+https://certiwatch.com/compliance-bot)',
  },
  {
    id: 'prov-fsc',
    code: 'FSC',
    name: 'Forest Stewardship Council (FSC Certificate Public Registry)',
    standards: ['FSC'],
    officialDomain: 'info.fsc.org',
    publicSearchUrl: 'https://info.fsc.org/certificate.php',
    apiAvailability: 'PARTNER_API_KEY_REQUIRED',
    rateLimitPolicy: 'API Partenaire FSC Connect (OAuth 2.0 / 120 req/min)',
    legalTermsSummary: 'Licence FSC requise pour intégration automatisée continue sans restriction.',
    status: 'OPERATIONAL',
    lastHealthCheck: '2026-09-24T06:50:00Z',
    avgResponseMs: 420,
    circuitBreakerState: 'CLOSED',
    consecutiveFailures: 0,
    monthlyRequestsCount: 920,
    monthlyQuota: 5000,
    uptimePercentage: 99.8,
    ethicalScrapingPolicy: 'Accès API Partenaire OAuth 2.0 certifié, respect des fenêtres de maintenance ASI',
    userAgentUsed: 'CertiWatch-FSC-Gateway/1.0 (Integration License FSC-PARTNER-889)',
  },
  {
    id: 'prov-gots',
    code: 'GOTS',
    name: 'Global Organic Textile Standard (GOTS Public Database)',
    standards: ['GOTS'],
    officialDomain: 'global-standard.org',
    publicSearchUrl: 'https://global-standard.org/find-suppliers-shops/certified-suppliers/database/search',
    apiAvailability: 'PUBLIC_REGISTRY_OPEN',
    rateLimitPolicy: 'Registre public officiel, quota de vérification 30 req/min',
    legalTermsSummary: 'Vérification autorisée des opérateurs certifiés et des licences GOTS.',
    status: 'OPERATIONAL',
    lastHealthCheck: '2026-09-24T07:00:00Z',
    avgResponseMs: 510,
    circuitBreakerState: 'CLOSED',
    consecutiveFailures: 0,
    monthlyRequestsCount: 640,
    monthlyQuota: 3000,
    uptimePercentage: 99.7,
    ethicalScrapingPolicy: 'Requêtes cadencées toutes les 2 secondes, pas de parallélisation agressive',
    userAgentUsed: 'CertiWatch-Compliance-Bot/1.0 (+https://certiwatch.com/compliance-bot)',
  },
  {
    id: 'prov-oekotex',
    code: 'OEKO_TEX',
    name: 'OEKO-TEX International (Label Check)',
    standards: ['OEKO_TEX_100', 'OEKO_TEX_STEP'],
    officialDomain: 'oeko-tex.com',
    publicSearchUrl: 'https://www.oeko-tex.com/en/label-check',
    apiAvailability: 'PUBLIC_REGISTRY_OPEN',
    rateLimitPolicy: 'Système officiel Label Check avec vérification directe des numéros de test',
    legalTermsSummary: 'Contrôle officiel de validité des certificats Standard 100 et STeP.',
    status: 'OPERATIONAL',
    lastHealthCheck: '2026-09-24T06:30:00Z',
    avgResponseMs: 390,
    circuitBreakerState: 'CLOSED',
    consecutiveFailures: 0,
    monthlyRequestsCount: 780,
    monthlyQuota: 5000,
    uptimePercentage: 99.9,
    ethicalScrapingPolicy: 'Vérification unitaire via formulaire de test officiel, mise en cache 7 jours',
    userAgentUsed: 'CertiWatch-Compliance-Bot/1.0 (+https://certiwatch.com/compliance-bot)',
  },
  {
    id: 'prov-fairtrade',
    code: 'FAIRTRADE',
    name: 'FLOCERT / Fairtrade International (Customer Search)',
    standards: ['FAIRTRADE'],
    officialDomain: 'flocert.net',
    publicSearchUrl: 'https://www.flocert.net/solutions/fairtrade-certification/customer-search/',
    apiAvailability: 'PUBLIC_REGISTRY_OPEN',
    rateLimitPolicy: 'Registre public des opérateurs FLO-ID certifiés',
    legalTermsSummary: 'Vérification des licences FLO et périmètres de produits équitables.',
    status: 'OPERATIONAL',
    lastHealthCheck: '2026-09-24T07:05:00Z',
    avgResponseMs: 480,
    circuitBreakerState: 'CLOSED',
    consecutiveFailures: 0,
    monthlyRequestsCount: 410,
    monthlyQuota: 2000,
    uptimePercentage: 99.8,
    ethicalScrapingPolicy: 'Consultation programmée aux heures creuses (02h00 - 05h00 UTC)',
    userAgentUsed: 'CertiWatch-Compliance-Bot/1.0 (+https://certiwatch.com/compliance-bot)',
  },
];

export const SEED_ORCHESTRATION_CONFIG: OrchestrationConfig = {
  frequency: 'DAILY',
  concurrency: 4,
  enableCircuitBreaker: true,
  cacheTtlHours: 24,
  autoTriggerErpBlockOnRevocation: true,
  lastRunTimestamp: '2026-09-24T06:00:00Z',
  nextScheduledRun: '2026-09-25T06:00:00Z',
};

export const SEED_ORCHESTRATOR_RUNS: OrchestratorRunLog[] = [
  {
    id: 'run-003',
    tenantId: 'tenant-danone-global',
    startedAt: '2026-09-24T06:00:00Z',
    completedAt: '2026-09-24T06:01:14Z',
    durationMs: 74200,
    totalCertsAudited: 7,
    matchesCount: 5,
    mismatchesCount: 2,
    revocationsDetected: 1,
    rateLimitHits: 0,
    status: 'SUCCESS',
    summary: 'Cycle quotidien exécuté avec succès. 1 alerte critique (FSC révoqué) et 1 divergence de date confirmées.',
  },
  {
    id: 'run-002',
    tenantId: 'tenant-danone-global',
    startedAt: '2026-09-23T06:00:00Z',
    completedAt: '2026-09-23T06:01:08Z',
    durationMs: 68100,
    totalCertsAudited: 7,
    matchesCount: 6,
    mismatchesCount: 1,
    revocationsDetected: 0,
    rateLimitHits: 0,
    status: 'SUCCESS',
    summary: 'Cycle quotidien sans anomalie nouvelle. 1 certificat Fairtrade arrivant à échéance sous 30 jours notifié.',
  },
  {
    id: 'run-001',
    tenantId: 'tenant-danone-global',
    startedAt: '2026-09-22T06:00:00Z',
    completedAt: '2026-09-22T06:01:25Z',
    durationMs: 85000,
    totalCertsAudited: 7,
    matchesCount: 7,
    mismatchesCount: 0,
    revocationsDetected: 0,
    rateLimitHits: 0,
    status: 'SUCCESS',
    summary: 'Cycle d’initialisation de surveillance continue exécuté pour l’ensemble des standards actifs.',
  },
];

export const SEED_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-danone-01',
    tenantId: 'tenant-danone-global',
    legalName: 'BioLait Normandie SAS',
    tradeName: 'Laiterie Bio de l’Orne',
    country: 'France',
    countryCode: 'FR',
    address: '12 Route des Bocages, 61100 Flers',
    internalId: 'SUP-FR-1042',
    businessRegistrationNumber: 'FR 84 412 876 201',
    contactName: 'Thierry Duval',
    contactEmail: 't.duval@biolait-normandie.fr',
    contactPhone: '+33 2 33 65 44 10',
    additionalContacts: [
      {
        id: 'c-danone-01-1',
        role: 'QUALITY',
        name: 'Thierry Duval',
        email: 't.duval@biolait-normandie.fr',
        phone: '+33 2 33 65 44 10',
        isPrimary: true,
      },
      {
        id: 'c-danone-01-2',
        role: 'CSR',
        name: 'Émilie Renaud',
        email: 'e.renaud@biolait-normandie.fr',
        phone: '+33 2 33 65 44 18',
        isPrimary: false,
      },
    ],
    productCategories: ['Lait Frais Bio', 'Crème Industrielle Bio'],
    status: 'ACTIVE',
    riskLevel: 'LOW',
    tier: 'TIER_1',
    spendCriticality: 'STRATEGIC',
    multiFactorRisk: {
      overallScore: 8,
      expirationScore: 0,
      revocationScore: 0,
      countryRiskScore: 3,
      coverageRiskScore: 5,
      riskFactors: ['Certificat Ecocert valide jusqu’en 2027', 'Périmètre 100% conforme'],
      recommendedActions: ['Maintenir surveillance standard continue', 'Prochain audit annuel planifié T1 2027'],
      lastCalculatedAt: '2026-09-24T06:12:00Z',
    },
    erpConfig: {
      erpSystem: 'SAP S/4HANA',
      erpVendorNumber: 'V-1004829',
      blockStatus: 'ALLOWED',
    },
    auditHistory: [
      {
        id: 'aud-bln-01',
        date: '2026-02-14',
        auditorName: 'Bureau Veritas (Danone QA Division)',
        auditType: 'ON_SITE_ANNUAL',
        score: 94,
        conclusion: 'COMPLIANT',
        capaStatus: 'COMPLETED',
        notes: 'Excellente traçabilité des lots de collecte laitière bio Normandie. Système d’échantillonnage conforme.',
        nextScheduledDate: '2027-02-15',
      },
      {
        id: 'aud-bln-00',
        date: '2025-01-18',
        auditorName: 'Ecocert France',
        auditType: 'THIRD_PARTY_AUDIT',
        score: 98,
        conclusion: 'COMPLIANT',
        capaStatus: 'NOT_APPLICABLE',
        notes: 'Audit de renouvellement de certificat FR-BIO-01 sans non-conformité.',
      },
    ],
    totalCertificatesCount: 2,
    validCertificatesCount: 2,
    criticalIssuesCount: 0,
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2026-09-22T14:00:00Z',
  },
  {
    id: 'sup-danone-02',
    tenantId: 'tenant-danone-global',
    legalName: 'Agrícola Andina del Cacao S.A.C.',
    tradeName: 'Andina Cocoa Peru',
    country: 'Pérou',
    countryCode: 'PE',
    address: 'Av. Circunvalación 450, Tarapoto, San Martín',
    internalId: 'SUP-PE-2041',
    businessRegistrationNumber: 'RUC 20491823901',
    contactName: 'Carlos M. Huaman',
    contactEmail: 'carlos@andinacocoa.pe',
    contactPhone: '+51 42 522 890',
    additionalContacts: [
      {
        id: 'c-danone-02-1',
        role: 'COMMERCIAL',
        name: 'Carlos M. Huaman',
        email: 'carlos@andinacocoa.pe',
        phone: '+51 42 522 890',
        isPrimary: true,
      },
      {
        id: 'c-danone-02-2',
        role: 'QUALITY',
        name: 'Rosa Palacios',
        email: 'qualite@andinacocoa.pe',
        phone: '+51 42 522 894',
        isPrimary: false,
      },
    ],
    productCategories: ['Cacao en Fèves', 'Beurre de Cacao Fairtrade'],
    status: 'ACTIVE',
    riskLevel: 'MEDIUM',
    tier: 'TIER_2',
    spendCriticality: 'MAJOR',
    multiFactorRisk: {
      overallScore: 56,
      expirationScore: 22,
      revocationScore: 10,
      countryRiskScore: 12,
      coverageRiskScore: 12,
      riskFactors: [
        'Certificat Fairtrade expire sous 28 jours (22/10/2026)',
        'Délai de transmission moyen supérieur à 45 jours',
        'Origine Amérique du Sud avec exigence de diligence raisonnée CSRD',
      ],
      recommendedActions: [
        'Envoyer relance urgente de renouvellement FLOCERT',
        'Exiger certificat de transaction (TC) pour la prochaine livraison',
      ],
      lastCalculatedAt: '2026-09-24T05:30:00Z',
    },
    erpConfig: {
      erpSystem: 'SAP S/4HANA',
      erpVendorNumber: 'V-2009184',
      blockStatus: 'TEMPORARY_DEROGATION',
      derogationExpiresAt: '2026-10-31',
      derogationJustification: 'Dérogation temporaire 30j accordée par Direction Achats sous réserve réception renouvellement FLOCERT.',
    },
    auditHistory: [
      {
        id: 'aud-aac-01',
        date: '2025-11-05',
        auditorName: 'FLOCERT Regional Inspectorate',
        auditType: 'DOCUMENTARY_AUDIT',
        score: 78,
        conclusion: 'MINOR_FINDINGS',
        capaStatus: 'IN_PROGRESS',
        notes: 'Plan d’action en cours sur la consolidation des registres des coopératives locales de San Martín.',
        nextScheduledDate: '2026-11-01',
      },
    ],
    totalCertificatesCount: 2,
    validCertificatesCount: 1,
    criticalIssuesCount: 1,
    createdAt: '2024-02-12T11:00:00Z',
    updatedAt: '2026-09-23T08:30:00Z',
  },
  {
    id: 'sup-danone-03',
    tenantId: 'tenant-danone-global',
    legalName: 'Cartonneries Européennes & Cellulose SA',
    tradeName: 'EuroCarton Packaging',
    country: 'Belgique',
    countryCode: 'BE',
    address: 'Zoning Industriel des Plaines 4, 7500 Tournai',
    internalId: 'SUP-BE-0078',
    businessRegistrationNumber: 'BE 0432.890.112',
    contactName: 'Philippe Janssens',
    contactEmail: 'p.janssens@eurocarton.be',
    contactPhone: '+32 69 77 12 30',
    additionalContacts: [
      {
        id: 'c-danone-03-1',
        role: 'COMMERCIAL',
        name: 'Philippe Janssens',
        email: 'p.janssens@eurocarton.be',
        phone: '+32 69 77 12 30',
        isPrimary: true,
      },
      {
        id: 'c-danone-03-2',
        role: 'QUALITY',
        name: 'Dirk Van Houten',
        email: 'd.vanhouten@eurocarton.be',
        isPrimary: false,
      },
    ],
    productCategories: ['Emballages Carton FSC', 'Pots Yaourt Carton'],
    status: 'BLOCKED',
    riskLevel: 'CRITICAL',
    tier: 'TIER_1',
    spendCriticality: 'STRATEGIC',
    multiFactorRisk: {
      overallScore: 94,
      expirationScore: 15,
      revocationScore: 40,
      countryRiskScore: 14,
      coverageRiskScore: 25,
      riskFactors: [
        'Certificat FSC révoqué pour rupture de chaîne de contrôle CoC',
        'Blocage strict des commandes d’achat actif dans SAP',
        'Risque réputationnel fort sur allégation d’emballage durable',
      ],
      recommendedActions: [
        'Maintenir le blocage immédiat des bons de commande SAP',
        'Transférer les volumes d’emballages sur fournisseur certifié secondaire',
        'Exiger audit de remédiation par organisme accrédité ASI',
      ],
      lastCalculatedAt: '2026-09-24T06:10:00Z',
    },
    erpConfig: {
      erpSystem: 'SAP S/4HANA',
      erpVendorNumber: 'V-0432890',
      blockStatus: 'BLOCKED',
      blockedReason: 'Certificat FSC révoqué par le certificateur pour non-conformité de chaîne de traçabilité.',
      blockedAt: '2026-09-24T06:10:00Z',
      blockedBy: 'CertiWatch Automated ERP Bridge',
    },
    auditHistory: [
      {
        id: 'aud-ec-01',
        date: '2026-08-10',
        auditorName: 'SGS Certification FSC',
        auditType: 'THIRD_PARTY_AUDIT',
        score: 42,
        conclusion: 'MAJOR_NON_CONFORMITY',
        capaStatus: 'OVERDUE',
        notes: 'Non-conformité majeure : inclusion de fibres non certifiées dans la ligne pots yaourts sans traçabilité.',
        nextScheduledDate: '2026-10-15',
      },
    ],
    totalCertificatesCount: 1,
    validCertificatesCount: 0,
    criticalIssuesCount: 1,
    erpBlockedReason: 'Certificat FSC révoqué par le certificateur pour non-conformité de chaîne de traçabilité.',
    createdAt: '2024-03-01T09:00:00Z',
    updatedAt: '2026-09-24T06:10:00Z',
  },
  {
    id: 'sup-danone-04',
    tenantId: 'tenant-danone-global',
    legalName: 'Polat Tarim Organik Gida San. Tic. Ltd.',
    tradeName: 'Polat Organic Fruits',
    country: 'Turquie',
    countryCode: 'TR',
    address: 'Organize Sanayi Bolgesi 3. Cadde No: 18, Malatya',
    internalId: 'SUP-TR-3392',
    businessRegistrationNumber: 'TR 731 092 4811',
    contactName: 'Kemal Polat',
    contactEmail: 'k.polat@polatorganic.com.tr',
    contactPhone: '+90 422 237 55 90',
    productCategories: ['Fruits Secs Bio', 'Purées d’Abricot Bio'],
    status: 'ON_HOLD',
    riskLevel: 'HIGH',
    tier: 'TIER_2',
    spendCriticality: 'MAJOR',
    multiFactorRisk: {
      overallScore: 81,
      expirationScore: 16,
      revocationScore: 35,
      countryRiskScore: 15,
      coverageRiskScore: 15,
      riskFactors: [
        'Statut de certificat suspendu au registre officiel Ecocert',
        'Suspicion de falsification ou non-concordance de validité de document PDF',
        'Audit de surveillance non validé',
      ],
      recommendedActions: [
        'Geler tout approvisionnement supplémentaire en purée de fruits',
        'Contacter Ecocert Istanbul pour vérification du procès-verbal',
      ],
      lastCalculatedAt: '2026-09-24T05:00:00Z',
    },
    erpConfig: {
      erpSystem: 'SAP S/4HANA',
      erpVendorNumber: 'V-7310924',
      blockStatus: 'BLOCKED',
      blockedReason: 'Mismatch détecté : Le certificat déposé mentionne Polat Tarim mais le registre Ecocert indique une suspension temporaire suite audit annuel.',
      blockedAt: '2026-09-24T05:00:00Z',
      blockedBy: 'CertiWatch Automated ERP Bridge',
    },
    auditHistory: [
      {
        id: 'aud-pt-01',
        date: '2026-07-20',
        auditorName: 'Ecocert Denetim TR',
        auditType: 'ON_SITE_ANNUAL',
        score: 64,
        conclusion: 'MAJOR_NON_CONFORMITY',
        capaStatus: 'IN_PROGRESS',
        notes: 'Suspension conservatoire suite à contamination résiduelle sur lot témoin.',
        nextScheduledDate: '2026-10-05',
      },
    ],
    totalCertificatesCount: 1,
    validCertificatesCount: 0,
    criticalIssuesCount: 1,
    erpBlockedReason: 'Mismatch détecté : Le certificat déposé mentionne Polat Tarim mais le registre Ecocert indique une suspension temporaire suite audit annuel.',
    createdAt: '2024-04-10T14:00:00Z',
    updatedAt: '2026-09-24T05:00:00Z',
  },
  {
    id: 'sup-danone-05',
    tenantId: 'tenant-danone-global',
    legalName: 'Sucreries & Distilleries Réunionnaises Bio',
    tradeName: 'Sucre des Mascareignes',
    country: 'France',
    countryCode: 'FR',
    address: 'Route de la Canne, 97470 Saint-Benoît, La Réunion',
    internalId: 'SUP-FR-5501',
    businessRegistrationNumber: 'FR 91 382 119 550',
    contactName: 'Mickaël Fontaine',
    contactEmail: 'm.fontaine@sucre-mascareignes.re',
    contactPhone: '+262 262 50 14 30',
    productCategories: ['Sucre Roux de Canne Bio', 'Mélasses'],
    status: 'ACTIVE',
    riskLevel: 'LOW',
    tier: 'TIER_3',
    spendCriticality: 'STANDARD',
    multiFactorRisk: {
      overallScore: 11,
      expirationScore: 0,
      revocationScore: 0,
      countryRiskScore: 4,
      coverageRiskScore: 7,
      riskFactors: ['Certificat Bio valide', 'Traçabilité des parcelles certifiée'],
      recommendedActions: ['Surveillance périodique standard'],
      lastCalculatedAt: '2026-09-21T11:00:00Z',
    },
    erpConfig: {
      erpSystem: 'SAP S/4HANA',
      erpVendorNumber: 'V-9138211',
      blockStatus: 'ALLOWED',
    },
    auditHistory: [
      {
        id: 'aud-sm-01',
        date: '2025-09-12',
        auditorName: 'Certipaq Bio Océan Indien',
        auditType: 'ON_SITE_ANNUAL',
        score: 96,
        conclusion: 'COMPLIANT',
        capaStatus: 'COMPLETED',
        notes: 'Filière canne à sucre certifiée sans aucune réserve.',
      },
    ],
    totalCertificatesCount: 1,
    validCertificatesCount: 1,
    criticalIssuesCount: 0,
    createdAt: '2024-05-18T10:30:00Z',
    updatedAt: '2026-09-21T11:00:00Z',
  },
  // Kering suppliers
  {
    id: 'sup-kering-01',
    tenantId: 'tenant-kering-luxury',
    legalName: 'Têxteis Guimarães & Filhos Lda',
    tradeName: 'Guimarães Textile Mills',
    country: 'Portugal',
    countryCode: 'PT',
    address: 'Rua das Lavouras 120, 4800 Guimarães',
    internalId: 'SUP-PT-9011',
    businessRegistrationNumber: 'PT 508 192 841',
    contactName: 'Manuel Guimarães',
    contactEmail: 'manuel@guimaraes-textiles.pt',
    contactPhone: '+351 253 421 900',
    productCategories: ['Coton Biologique Peigné', 'Jersey GOTS'],
    status: 'ACTIVE',
    riskLevel: 'LOW',
    totalCertificatesCount: 2,
    validCertificatesCount: 2,
    criticalIssuesCount: 0,
    createdAt: '2024-02-15T09:00:00Z',
    updatedAt: '2026-09-22T10:00:00Z',
  },
];

export const SEED_CERTIFICATES: Certificate[] = [
  // 1. Valid certificate with 100% match
  {
    id: 'cert-danone-01',
    tenantId: 'tenant-danone-global',
    supplierId: 'sup-danone-01',
    supplierName: 'BioLait Normandie SAS',
    certificationStandard: 'ECOCERT_BIO',
    standardLabel: 'Ecocert Agriculture Biologique (FR-BIO-01)',
    certificationBody: 'Ecocert France SAS',
    certificateNumber: 'FR-BIO-01-2024-118942',
    issueDate: '2025-01-10',
    expiryDate: '2027-01-09',
    status: 'VALID',
    scope: {
      geographicalRegions: ['France (Normandie)'],
      productCategories: ['Produits laitiers et dérivés'],
      coveredProducts: ['Lait cru biologique', 'Lait demi-écrémé UHT', 'Crème fraîche 35% bio'],
      coveredFacilities: ['Usine de Flers (Agrément FR 61.169.001 CE)', 'Centre de collecte Vire'],
    },
    officialRegistryUrl: 'https://certificat.ecocert.com/search?q=FR-BIO-01-2024-118942',
    lastVerifiedAt: '2026-09-24T06:12:00Z',
    nextVerificationScheduledAt: '2026-09-25T06:00:00Z',
    verificationOutcome: 'MATCH',
    confidenceScore: 100,
    confidenceReasons: [
      'Numéro de certificat FR-BIO-01-2024-118942 confirmé au registre Ecocert',
      'Raison sociale exacte : BioLait Normandie SAS',
      'Périmètre produit conforme (Lait cru bio et dérivés)',
      'Dates d’effet et de fin valides au 24/09/2026',
    ],
    anomalies: [],
    originalDocumentName: 'Certificat_Bio_Ecocert_Biolait_2025_2027.pdf',
    fileSizeBytes: 245012,
    uploadedAt: '2025-01-15T14:22:00Z',
    uploadedByUserId: 'usr-qm-1',
    rawOcrTextSnippet: 'ECOCERT France SAS atteste que l’opérateur BioLait Normandie SAS, N° Siren 412876201...',
    notes: 'Certificat renouvelé sans réserve après audit de surveillance annuel.',
  },
  // 2. Expiring soon in 28 days
  {
    id: 'cert-danone-02',
    tenantId: 'tenant-danone-global',
    supplierId: 'sup-danone-02',
    supplierName: 'Agrícola Andina del Cacao S.A.C.',
    certificationStandard: 'FAIRTRADE',
    standardLabel: 'Fairtrade / Max Havelaar (FLO-CERT)',
    certificationBody: 'FLOCERT GmbH',
    certificateNumber: 'FLO-ID-34891',
    issueDate: '2023-10-22',
    expiryDate: '2026-10-22', // Expiring in 28 days relative to 2026-09-24
    status: 'EXPIRING_SOON',
    scope: {
      geographicalRegions: ['Pérou (Région San Martín)'],
      productCategories: ['Cacao et dérivés équitables'],
      coveredProducts: ['Fèves de cacao fermentées et séchées Fairtrade', 'Pâte de cacao pure'],
      coveredFacilities: ['Planta de Procesamiento Tarapoto km 8.5'],
    },
    officialRegistryUrl: 'https://www.flocert.net/solutions/fairtrade-certification/customer-search/?floId=34891',
    lastVerifiedAt: '2026-09-24T05:30:00Z',
    nextVerificationScheduledAt: '2026-09-25T05:00:00Z',
    verificationOutcome: 'MATCH',
    confidenceScore: 94,
    confidenceReasons: [
      'FLO-ID 34891 actif dans la base FLOCERT',
      'Titulaire certifié : Agrícola Andina del Cacao S.A.C.',
      'Avertissement : Date d’expiration dans 28 jours (22/10/2026)',
    ],
    anomalies: [
      {
        field: 'EXPIRY_DATE',
        documentValue: '2026-10-22',
        officialValue: '2026-10-22',
        severity: 'WARNING',
        description: 'Le certificat expire dans 28 jours. Le renouvellement doit être initié immédiatement auprès de FLOCERT.',
      },
    ],
    originalDocumentName: 'FLO_Cert_Andina_Cocoa_2023_2026.pdf',
    fileSizeBytes: 312890,
    uploadedAt: '2023-11-01T10:15:00Z',
    uploadedByUserId: 'usr-qm-1',
    rawOcrTextSnippet: 'FLOCERT GmbH hereby certifies that Agrícola Andina del Cacao S.A.C., FLO ID 34891...',
    notes: 'Relance envoyée au fournisseur Carlos Huaman le 20/09/2026.',
  },
  // 3. Revoked FSC Certificate -> Blocking procurement!
  {
    id: 'cert-danone-03',
    tenantId: 'tenant-danone-global',
    supplierId: 'sup-danone-03',
    supplierName: 'Cartonneries Européennes & Cellulose SA',
    certificationStandard: 'FSC',
    standardLabel: 'FSC Chain of Custody (FSC-C104928)',
    certificationBody: 'Bureau Veritas Certification Forest',
    certificateNumber: 'BV-COC-104928',
    issueDate: '2024-04-01',
    expiryDate: '2029-03-31',
    status: 'REVOKED',
    scope: {
      geographicalRegions: ['Union Européenne'],
      productCategories: ['Emballages cartons et papiers kraft'],
      coveredProducts: ['Carton ondulé FSC Mix 70%', 'Boîtes pliantes alimentaires'],
      coveredFacilities: ['Site de Tournai Nord'],
    },
    officialRegistryUrl: 'https://info.fsc.org/certificate.php?id=BV-COC-104928',
    lastVerifiedAt: '2026-09-24T06:05:00Z',
    nextVerificationScheduledAt: '2026-09-24T12:00:00Z',
    verificationOutcome: 'MISMATCH',
    confidenceScore: 35,
    confidenceReasons: [
      'Le registre public FSC affiche le statut officiel "Terminated / Revoked" en date du 18/09/2026',
      'Le document PDF soumis par le fournisseur mentionnait une validité jusqu’en 2029 sans mention de la sanction',
    ],
    anomalies: [
      {
        field: 'STATUS',
        documentValue: 'VALID (jusqu’au 31/03/2029)',
        officialValue: 'TERMINATED / REVOKED (au 18/09/2026)',
        severity: 'CRITICAL',
        description: 'RÉVOCATION OFFICIELLE : FSC International a révoqué la licence suite à rupture de chaîne de contrôle de pâte à papier.',
      },
    ],
    originalDocumentName: 'Certificat_FSC_EuroCarton_2024.pdf',
    fileSizeBytes: 420100,
    uploadedAt: '2024-04-12T16:00:00Z',
    uploadedByUserId: 'usr-pm-1',
    rawOcrTextSnippet: 'Bureau Veritas certifies FSC-STD-40-004 Cartonneries Europeennes BV-COC-104928...',
    notes: 'COMMANDE AUTOMATIQUEMENT BLOQUÉE DANS L’ERP VIA API CERTIWATCH.',
  },
  // 4. Mismatch detected between document and official registry
  {
    id: 'cert-danone-04',
    tenantId: 'tenant-danone-global',
    supplierId: 'sup-danone-04',
    supplierName: 'Polat Tarim Organik Gida San. Tic. Ltd.',
    certificationStandard: 'ECOCERT_BIO',
    standardLabel: 'Ecocert Organic Standard (TR-BIO-154)',
    certificationBody: 'Ecocert Denetim ve Belgelendirme Ltd.',
    certificateNumber: 'TR-BIO-154-88401',
    issueDate: '2024-06-01',
    expiryDate: '2026-11-30',
    status: 'SUSPENDED',
    scope: {
      geographicalRegions: ['Turquie'],
      productCategories: ['Fruits transformés biologiques'],
      coveredProducts: ['Purées d’abricots bio', 'Abricots séchés bio'],
      coveredFacilities: ['Malatya Processing Unit 2'],
    },
    officialRegistryUrl: 'https://certificat.ecocert.com/search?q=TR-BIO-154-88401',
    lastVerifiedAt: '2026-09-24T05:00:00Z',
    nextVerificationScheduledAt: '2026-09-24T17:00:00Z',
    verificationOutcome: 'MISMATCH',
    confidenceScore: 45,
    confidenceReasons: [
      'Le registre Ecocert indique "Statut : Suspendu temporairement" suite à analyse résiduelle non conforme',
      'Le document fourni présente un statut apparemment valide',
    ],
    anomalies: [
      {
        field: 'STATUS',
        documentValue: 'VALID',
        officialValue: 'SUSPENDED',
        severity: 'CRITICAL',
        description: 'Divergence critique : Le registre officiel Ecocert atteste d’une suspension en vigueur depuis le 05/09/2026.',
      },
    ],
    originalDocumentName: 'Ecocert_Polat_Organic_2024.pdf',
    fileSizeBytes: 189000,
    uploadedAt: '2024-06-15T09:40:00Z',
    uploadedByUserId: 'usr-qm-1',
    rawOcrTextSnippet: 'ECOCERT Denetim belgesi TR-BIO-154 Polat Tarim Organik Gida...',
    notes: 'Lot de purée d’abricots mis en quarantaine qualité.',
  },
  // 5. Expired certificate
  {
    id: 'cert-danone-05',
    tenantId: 'tenant-danone-global',
    supplierId: 'sup-danone-02',
    supplierName: 'Agrícola Andina del Cacao S.A.C.',
    certificationStandard: 'ECOCERT_BIO',
    standardLabel: 'Ecocert Organic Standard (NOP / UE)',
    certificationBody: 'Ecocert Americas',
    certificateNumber: 'PE-BIO-154-44210',
    issueDate: '2023-08-01',
    expiryDate: '2025-07-31', // Already expired over 1 year ago!
    status: 'EXPIRED',
    scope: {
      geographicalRegions: ['Pérou'],
      productCategories: ['Cacao'],
      coveredProducts: ['Cacao biologique'],
      coveredFacilities: ['Tarapoto'],
    },
    officialRegistryUrl: 'https://certificat.ecocert.com/search?q=PE-BIO-154-44210',
    lastVerifiedAt: '2026-09-24T04:20:00Z',
    nextVerificationScheduledAt: '2026-09-25T04:00:00Z',
    verificationOutcome: 'MATCH',
    confidenceScore: 90,
    confidenceReasons: [
      'Certificat archivé dans le registre officiel avec date de fin échue au 31/07/2025',
      'Aucun nouveau certificat de remplacement déposé dans le portail',
    ],
    anomalies: [
      {
        field: 'EXPIRY_DATE',
        documentValue: '2025-07-31',
        officialValue: '2025-07-31',
        severity: 'CRITICAL',
        description: 'Certificat expiré depuis 420 jours. Risque de non-conformité majeure sur les approvisionnements de cacao bio péruvien.',
      },
    ],
    originalDocumentName: 'Certificat_Ecocert_Bio_Andina_Old.pdf',
    fileSizeBytes: 290140,
    uploadedAt: '2023-08-10T11:00:00Z',
    uploadedByUserId: 'usr-qm-1',
    rawOcrTextSnippet: 'ECOCERT Organic Certificate PE-BIO-154 valid until 31 July 2025...',
    notes: 'Demande expresse transmise aux achats pour actualisation.',
  },
  // 6. Kering: GOTS valid certificate
  {
    id: 'cert-kering-01',
    tenantId: 'tenant-kering-luxury',
    supplierId: 'sup-kering-01',
    supplierName: 'Têxteis Guimarães & Filhos Lda',
    certificationStandard: 'GOTS',
    standardLabel: 'Global Organic Textile Standard Version 7.0',
    certificationBody: 'Control Union Certifications B.V.',
    certificateNumber: 'CU-849301-GOTS-2024-01',
    issueDate: '2024-11-01',
    expiryDate: '2027-10-31',
    status: 'VALID',
    scope: {
      geographicalRegions: ['Portugal', 'Union Européenne'],
      productCategories: ['Textiles biologiques haut de gamme'],
      coveredProducts: ['Fil de coton biologique peigné 100% GOTS', 'Tricot jersey biologique certifié'],
      coveredFacilities: ['Unidade Fabril Guimarães Norte (CU Lic. 849301)'],
    },
    officialRegistryUrl: 'https://global-standard.org/find-suppliers-shops/certified-suppliers/database/search?licenseNumber=849301',
    lastVerifiedAt: '2026-09-24T06:00:00Z',
    nextVerificationScheduledAt: '2026-09-25T06:00:00Z',
    verificationOutcome: 'MATCH',
    confidenceScore: 98,
    confidenceReasons: [
      'Licence Control Union CU-849301 active dans la base centrale GOTS',
      'Périmètre produit conforme (Coton 100% GOTS)',
      'Site audité et conforme aux exigences sociales et chimiques GOTS 7.0',
    ],
    anomalies: [],
    originalDocumentName: 'GOTS_Scope_Certificate_Guimaraes_2024.pdf',
    fileSizeBytes: 512090,
    uploadedAt: '2024-11-10T15:30:00Z',
    uploadedByUserId: 'usr-kering-1',
    rawOcrTextSnippet: 'Control Union Certifications Scope Certificate CU849301GOTS Texteis Guimaraes...',
    notes: 'Excellente notation d’audit RSE.',
  },
  // 7. Kering: OEKO-TEX Standard 100
  {
    id: 'cert-kering-02',
    tenantId: 'tenant-kering-luxury',
    supplierId: 'sup-kering-01',
    supplierName: 'Têxteis Guimarães & Filhos Lda',
    certificationStandard: 'OEKO_TEX_100',
    standardLabel: 'OEKO-TEX Standard 100 Classe I (Articles bébé & peaux sensibles)',
    certificationBody: 'CITEVE Portugal',
    certificateNumber: 'OEKO-8419-CIT',
    issueDate: '2024-10-15',
    expiryDate: '2026-11-05', // Expiring in 42 days!
    status: 'EXPIRING_SOON',
    scope: {
      geographicalRegions: ['Portugal'],
      productCategories: ['Articles textiles sans substances nocives'],
      coveredProducts: ['Tissus tricotés en coton écru, blanc et teints réactifs'],
      coveredFacilities: ['Guimarães Teinturerie & Finition'],
    },
    officialRegistryUrl: 'https://www.oeko-tex.com/en/label-check?cert=8419CIT',
    lastVerifiedAt: '2026-09-24T06:40:00Z',
    nextVerificationScheduledAt: '2026-09-25T06:00:00Z',
    verificationOutcome: 'MATCH',
    confidenceScore: 96,
    confidenceReasons: [
      'Numéro de certificat 8419CIT confirmé sur OEKO-TEX Label Check',
      'Validité jusqu’au 05/11/2026 (Expire dans 42 jours)',
    ],
    anomalies: [
      {
        field: 'EXPIRY_DATE',
        documentValue: '2026-11-05',
        officialValue: '2026-11-05',
        severity: 'WARNING',
        description: 'Certificat OEKO-TEX expirant sous 42 jours. Renouvellement annuel des tests en laboratoire requis.',
      },
    ],
    originalDocumentName: 'OekoTex_Standard100_Guimaraes_2025.pdf',
    fileSizeBytes: 380450,
    uploadedAt: '2024-10-20T11:00:00Z',
    uploadedByUserId: 'usr-kering-1',
    rawOcrTextSnippet: 'OEKO-TEX Association certifies that Texteis Guimaraes has been tested according to Standard 100...',
    notes: 'Dossier de renouvellement transmis au CITEVE le 15/09/2026.',
  },
];

export const SEED_ALERTS: ComplianceAlert[] = [
  {
    id: 'alt-danone-01',
    tenantId: 'tenant-danone-global',
    certificateId: 'cert-danone-03',
    supplierId: 'sup-danone-03',
    supplierName: 'Cartonneries Européennes & Cellulose SA',
    certificationStandard: 'FSC',
    certificateNumber: 'BV-COC-104928',
    type: 'REVOKED',
    title: 'Révocation critique du certificat FSC',
    message: 'Le certificat FSC BV-COC-104928 a été officiellement révoqué par Bureau Veritas / FSC International pour rupture de chaîne de contrôle. Toutes les commandes d’emballages associées sont gelées.',
    severity: 'CRITICAL',
    status: 'OPEN',
    assignedToUser: 'Sarah Benali',
    erpBlockedTriggered: true,
    history: [
      {
        id: 'act-1',
        performedBy: 'CertiWatch Automated Registry Sync (FSC)',
        actionType: 'STATUS_CHANGED',
        comment: 'Détection automatique de la révocation sur le registre officiel info.fsc.org. Blocage ERP appliqué.',
        createdAt: '2026-09-24T06:05:00Z',
      },
    ],
    createdAt: '2026-09-24T06:05:00Z',
    updatedAt: '2026-09-24T06:05:00Z',
  },
  {
    id: 'alt-danone-02',
    tenantId: 'tenant-danone-global',
    certificateId: 'cert-danone-04',
    supplierId: 'sup-danone-04',
    supplierName: 'Polat Tarim Organik Gida San. Tic. Ltd.',
    certificationStandard: 'ECOCERT_BIO',
    certificateNumber: 'TR-BIO-154-88401',
    type: 'SUSPENDED',
    title: 'Suspension officielle sur registre Ecocert',
    message: 'Divergence critique : le document fourni indique une validité en cours, mais le registre Ecocert officiel déclare le certificat SUSPENDU suite à contrôle inopiné.',
    severity: 'CRITICAL',
    status: 'OPEN',
    assignedToUser: 'Julien Lefebvre',
    erpBlockedTriggered: true,
    history: [
      {
        id: 'act-2',
        performedBy: 'CertiWatch AI Comparator',
        actionType: 'STATUS_CHANGED',
        comment: 'Anomalie détectée entre le document et la source officielle. Statut passé à SUSPENDED.',
        createdAt: '2026-09-24T05:00:00Z',
      },
    ],
    createdAt: '2026-09-24T05:00:00Z',
    updatedAt: '2026-09-24T05:00:00Z',
  },
  {
    id: 'alt-danone-03',
    tenantId: 'tenant-danone-global',
    certificateId: 'cert-danone-02',
    supplierId: 'sup-danone-02',
    supplierName: 'Agrícola Andina del Cacao S.A.C.',
    certificationStandard: 'FAIRTRADE',
    certificateNumber: 'FLO-ID-34891',
    type: 'EXPIRY_30_DAYS',
    title: 'Certificat Fairtrade expire dans 28 jours',
    message: 'Le certificat Fairtrade FLO-ID-34891 expire le 22/10/2026. Risque d’arrêt des approvisionnements cacao équitable si le renouvellement n’est pas fourni avant échéance.',
    severity: 'HIGH',
    status: 'IN_PROGRESS',
    assignedToUser: 'Sarah Benali',
    erpBlockedTriggered: false,
    history: [
      {
        id: 'act-3',
        performedBy: 'CertiWatch Scheduler',
        actionType: 'STATUS_CHANGED',
        comment: 'Seuil des 30 jours franchi.',
        createdAt: '2026-09-22T00:01:00Z',
      },
      {
        id: 'act-4',
        performedBy: 'Sarah Benali',
        actionType: 'DOCUMENT_REQUESTED',
        comment: 'Email automatique et relance envoyés au directeur d’exploitation Carlos Huaman.',
        createdAt: '2026-09-22T09:15:00Z',
      },
    ],
    createdAt: '2026-09-22T00:01:00Z',
    updatedAt: '2026-09-22T09:15:00Z',
  },
  {
    id: 'alt-danone-04',
    tenantId: 'tenant-danone-global',
    certificateId: 'cert-danone-05',
    supplierId: 'sup-danone-02',
    supplierName: 'Agrícola Andina del Cacao S.A.C.',
    certificationStandard: 'ECOCERT_BIO',
    certificateNumber: 'PE-BIO-154-44210',
    type: 'EXPIRED',
    title: 'Certificat Ecocert Bio expiré non renouvelé',
    message: 'Le certificat bio péruvien PE-BIO-154-44210 est arrivé à expiration et n’a pas été remplacé. Tous les approvisionnements sous allégation "Bio" sont bloqués.',
    severity: 'HIGH',
    status: 'OPEN',
    assignedToUser: 'Julien Lefebvre',
    erpBlockedTriggered: true,
    history: [],
    createdAt: '2026-09-20T08:00:00Z',
    updatedAt: '2026-09-20T08:00:00Z',
  },
];

export const SEED_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'log-101',
    tenantId: 'tenant-danone-global',
    timestamp: '2026-09-24T06:05:00Z',
    userId: 'system-sync',
    userName: 'Système Automatisé (Connecteur FSC)',
    userRole: 'SYSTEM',
    actionCategory: 'CERTIFICATE_STATUS_CHANGED',
    entityType: 'CERTIFICATE',
    entityId: 'cert-danone-03',
    entityReference: 'FSC BV-COC-104928 (Cartonneries Européennes)',
    source: 'AUTOMATED_SYNC',
    previousValue: 'VALID',
    newValue: 'REVOKED',
    details: 'Synchronisation du registre officiel FSC (info.fsc.org) : Statut mis à jour vers REVOKED suite à suspension du certificat.',
    ipAddress: '10.0.4.12',
    blockNumber: 5,
    previousHash: 'b4a8e32918dfc47101ad4f810e82c5a772b109e4a9058b4389d4e12fa8723c10',
    hash: 'fa920d3678129e71b56a472c918ef0132b4908df31cb98a729e84019fa308e71',
    digitalSeal: 'CERT-SEAL-FA920D3678129E71-ED25519-AUTH',
  },
  {
    id: 'log-102',
    tenantId: 'tenant-danone-global',
    timestamp: '2026-09-24T06:05:02Z',
    userId: 'system-erp',
    userName: 'CertiWatch ERP Connector',
    userRole: 'SYSTEM',
    actionCategory: 'ERP_BLOCK_TRIGGERED',
    entityType: 'SUPPLIER',
    entityId: 'sup-danone-03',
    entityReference: 'Cartonneries Européennes & Cellulose SA',
    source: 'ERP_WEBHOOK',
    previousValue: 'ACTIVE',
    newValue: 'BLOCKED',
    details: 'Webhook ERP SAP déclenché : Statut fournisseur passé à BLOCKED suite à la révocation du certificat FSC.',
    ipAddress: '10.0.4.12',
    blockNumber: 4,
    previousHash: 'a718c3924ef089b12a3d7e5518b0492f190e38d74ca291845189b27419e048df',
    hash: 'b4a8e32918dfc47101ad4f810e82c5a772b109e4a9058b4389d4e12fa8723c10',
    digitalSeal: 'CERT-SEAL-B4A8E32918DFC471-ED25519-AUTH',
  },
  {
    id: 'log-103',
    tenantId: 'tenant-danone-global',
    timestamp: '2026-09-24T05:00:00Z',
    userId: 'system-sync',
    userName: 'Système Automatisé (Connecteur Ecocert)',
    userRole: 'SYSTEM',
    actionCategory: 'CERTIFICATE_STATUS_CHANGED',
    entityType: 'CERTIFICATE',
    entityId: 'cert-danone-04',
    entityReference: 'TR-BIO-154-88401 (Polat Tarim)',
    source: 'AUTOMATED_SYNC',
    previousValue: 'VALID',
    newValue: 'SUSPENDED',
    details: 'Détection d’une anomalie critique entre le document archivé et le registre public Ecocert. Statut suspendu.',
    ipAddress: '10.0.4.12',
    blockNumber: 3,
    previousHash: '72e903a48bf1290e54cd8912ef389410ea82914bf190e8234190ba824910ef39',
    hash: 'a718c3924ef089b12a3d7e5518b0492f190e38d74ca291845189b27419e048df',
    digitalSeal: 'CERT-SEAL-A718C3924EF089B1-ED25519-AUTH',
  },
  {
    id: 'log-104',
    tenantId: 'tenant-danone-global',
    timestamp: '2026-09-23T14:20:00Z',
    userId: 'usr-qm-1',
    userName: 'Julien Lefebvre',
    userRole: 'QUALITY_MANAGER',
    actionCategory: 'CERTIFICATE_VERIFIED',
    entityType: 'CERTIFICATE',
    entityId: 'cert-danone-01',
    entityReference: 'FR-BIO-01-2024-118942 (BioLait Normandie)',
    source: 'MANUAL_UI',
    previousValue: 'PENDING',
    newValue: 'MATCH',
    details: 'Vérification manuelle déclenchée depuis le portail. 100% de concordance validée.',
    ipAddress: '194.254.12.8',
    blockNumber: 2,
    previousHash: '0000000000000000000000000000000000000000000000000000000000000000',
    hash: '72e903a48bf1290e54cd8912ef389410ea82914bf190e8234190ba824910ef39',
    digitalSeal: 'CERT-SEAL-72E903A48BF1290E-ED25519-AUTH',
  },
  {
    id: 'log-105',
    tenantId: 'tenant-danone-global',
    timestamp: '2026-09-22T09:15:00Z',
    userId: 'usr-pm-1',
    userName: 'Sarah Benali',
    userRole: 'PROCUREMENT_MANAGER',
    actionCategory: 'ALERT_TRIGGERED',
    entityType: 'ALERT',
    entityId: 'alt-danone-03',
    entityReference: 'Alerte Expiration Fairtrade 30j (Agrícola Andina)',
    source: 'MANUAL_UI',
    previousValue: 'OPEN',
    newValue: 'IN_PROGRESS',
    details: 'Prise en charge de l’alerte et demande expresse de renouvellement transmise au fournisseur.',
    ipAddress: '194.254.12.9',
    blockNumber: 1,
    previousHash: '0000000000000000000000000000000000000000000000000000000000000000',
    hash: '0000000000000000000000000000000000000000000000000000000000000000',
    digitalSeal: 'CERT-SEAL-GENESIS-DANONE-ED25519',
  },
];

export const SEED_COMPLIANCE_MATRIX: ComplianceMatrixRule[] = [
  {
    id: 'rule-danone-01',
    tenantId: 'tenant-danone-global',
    productCategory: 'Produits Laitiers Biologiques',
    requiredStandards: ['ECOCERT_BIO'],
    acceptableAlternativeStandards: [],
    criticality: 'STRICT_BLOCK',
    countryCondition: 'ALL_COUNTRIES',
    enforceFacilityAudit: true,
    volumeThreshold: { enabled: false, minAnnualSpendEur: 0 },
    notes: 'Exigence réglementaire européenne CE 2018/848. Aucun approvisionnement autorisé sans certificat bio valide couvrant les sites d’élevage et d’embouteillage.',
    updatedAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'rule-danone-02',
    tenantId: 'tenant-danone-global',
    productCategory: 'Emballages Primaires Carton & Papier',
    requiredStandards: ['FSC'],
    acceptableAlternativeStandards: ['PEFC'],
    criticality: 'STRICT_BLOCK',
    countryCondition: 'ALL_COUNTRIES',
    enforceFacilityAudit: false,
    volumeThreshold: { enabled: false, minAnnualSpendEur: 0 },
    notes: 'Politique Zéro Déforestation Danone 2030 : certification FSC Chain of Custody ou PEFC obligatoire sur tout emballage en contact alimentaire.',
    updatedAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'rule-danone-03',
    tenantId: 'tenant-danone-global',
    productCategory: 'Cacao & Dérivés Filière Sud',
    requiredStandards: ['FAIRTRADE'],
    acceptableAlternativeStandards: ['ECOCERT_BIO'],
    criticality: 'STRICT_BLOCK',
    countryCondition: 'NON_EU_ONLY',
    enforceFacilityAudit: true,
    volumeThreshold: { enabled: true, minAnnualSpendEur: 20000 },
    notes: 'Approvisionnements responsables : certification Fairtrade / Max Havelaar obligatoire dès 20 000 € d’achats pour tout fournisseur situé hors Union Européenne.',
    updatedAt: '2026-08-15T14:30:00Z',
  },
  {
    id: 'rule-danone-04',
    tenantId: 'tenant-danone-global',
    productCategory: 'Fruits Secs & Purées Bio',
    requiredStandards: ['ECOCERT_BIO'],
    acceptableAlternativeStandards: [],
    criticality: 'STRICT_BLOCK',
    countryCondition: 'ALL_COUNTRIES',
    enforceFacilityAudit: true,
    volumeThreshold: { enabled: false, minAnnualSpendEur: 0 },
    notes: 'Obligation de certification de l’atelier de transformation et de pasteurisation (les simples vergers agricoles ne suffisent pas).',
    updatedAt: '2026-08-20T09:00:00Z',
  },
  {
    id: 'rule-danone-05',
    tenantId: 'tenant-danone-global',
    productCategory: 'Sucre de Canne & Édulcorants Bio',
    requiredStandards: ['ECOCERT_BIO'],
    acceptableAlternativeStandards: ['FAIRTRADE'],
    criticality: 'WARNING_ONLY',
    countryCondition: 'ALL_COUNTRIES',
    enforceFacilityAudit: false,
    volumeThreshold: { enabled: false, minAnnualSpendEur: 0 },
    notes: 'Priorité bio avec tolérance équitable sous réserve d’approbation de la direction achats.',
    updatedAt: '2026-09-01T11:00:00Z',
  },
  // Kering rules
  {
    id: 'rule-kering-01',
    tenantId: 'tenant-kering-luxury',
    productCategory: 'Coton & Fibres Végétales',
    requiredStandards: ['GOTS'],
    acceptableAlternativeStandards: ['GRS'],
    criticality: 'STRICT_BLOCK',
    countryCondition: 'ALL_COUNTRIES',
    enforceFacilityAudit: true,
    volumeThreshold: { enabled: false, minAnnualSpendEur: 0 },
    notes: 'Standard Kering Matières Premières Durables : Coton 100% biologique certifié GOTS exigé pour toutes les Maisons du groupe.',
    updatedAt: '2026-07-20T11:00:00Z',
  },
  {
    id: 'rule-kering-02',
    tenantId: 'tenant-kering-luxury',
    productCategory: 'Teintures & Façonnage Textile',
    requiredStandards: ['OEKO_TEX_100'],
    acceptableAlternativeStandards: ['OEKO_TEX_STEP'],
    criticality: 'STRICT_BLOCK',
    countryCondition: 'ALL_COUNTRIES',
    enforceFacilityAudit: true,
    volumeThreshold: { enabled: false, minAnnualSpendEur: 0 },
    notes: 'Réglementation REACH & innocuité : conformité OEKO-TEX Standard 100 obligatoire sur tous les textiles teints.',
    updatedAt: '2026-07-22T14:00:00Z',
  },
];

// --- EUDR (EU Deforestation Regulation) Initial Plot Declarations ---
export const SEED_EUDR_PLOTS: EudrPlotDeclaration[] = [
  {
    id: 'eudr-plot-01',
    supplierId: 'sup-danone-02', // Agrícola Andina del Cacao S.A.C.
    commodity: 'COCOA',
    countryOfProduction: 'Pérou (San Martín / Tocache)',
    plotReference: 'PER-SM-TOC-2024-LOT-44B',
    hasGpsCoordinates: true,
    gpsPolygonOrPoint: '-8.18721, -76.51442 (Polygone 14.8 ha)',
    deforestationCutoffDateMet: true, // No deforestation after Dec 31, 2020
    legalityVerified: true,
    tracesNtDdsReference: 'DDS-EUDR-2026-PE-098842',
    status: 'COMPLIANT',
    riskAssessment: 'STANDARD',
    verifiedAt: '2026-08-14T10:30:00Z',
  },
  {
    id: 'eudr-plot-02',
    supplierId: 'sup-danone-02', // Agrícola Andina del Cacao S.A.C.
    commodity: 'COCOA',
    countryOfProduction: 'Pérou (Ucayali / Coronel Portillo)',
    plotReference: 'PER-UC-CP-2025-PARC-12A',
    hasGpsCoordinates: false,
    gpsPolygonOrPoint: 'Coordonnées GPS incomplètes (Manque polygone de délimitation > 4ha)',
    deforestationCutoffDateMet: true,
    legalityVerified: false,
    tracesNtDdsReference: undefined,
    status: 'WARNING_DATA_MISSING',
    riskAssessment: 'HIGH',
    verifiedAt: '2026-09-02T14:15:00Z',
  },
  {
    id: 'eudr-plot-03',
    supplierId: 'sup-danone-03', // Cartonneries Européennes & Cellulose SA
    commodity: 'WOOD_TIMBER',
    countryOfProduction: 'Suède (Dalarna / Siljan Forest)',
    plotReference: 'SWE-DAL-SIL-FSC-8812',
    hasGpsCoordinates: true,
    gpsPolygonOrPoint: '60.85241, 14.98124 (Polygone Forêt Certifiée 320 ha)',
    deforestationCutoffDateMet: true,
    legalityVerified: true,
    tracesNtDdsReference: 'DDS-EUDR-2026-SE-441091',
    status: 'COMPLIANT',
    riskAssessment: 'NEGLIGIBLE',
    verifiedAt: '2026-08-25T09:00:00Z',
  },
  {
    id: 'eudr-plot-04',
    supplierId: 'sup-danone-03', // Cartonneries Européennes & Cellulose SA
    commodity: 'PAPER_PACKAGING',
    countryOfProduction: 'France (Massif Vosgien)',
    plotReference: 'FRA-VOS-GER-2024-001',
    hasGpsCoordinates: true,
    gpsPolygonOrPoint: '48.07210, 6.87410 (Polygone PEFC 85 ha)',
    deforestationCutoffDateMet: true,
    legalityVerified: true,
    tracesNtDdsReference: 'DDS-EUDR-2026-FR-112044',
    status: 'COMPLIANT',
    riskAssessment: 'NEGLIGIBLE',
    verifiedAt: '2026-09-10T16:20:00Z',
  },
  {
    id: 'eudr-plot-05',
    supplierId: 'sup-danone-05', // Sucreries & Distilleries Réunionnaises Bio
    commodity: 'SOY',
    countryOfProduction: 'Brésil (Mato Grosso / Sorriso)',
    plotReference: 'BRA-MT-SOR-2025-EXT-99C',
    hasGpsCoordinates: true,
    gpsPolygonOrPoint: '-12.54210, -55.71230 (Polygone 450 ha)',
    deforestationCutoffDateMet: false, // Deforestation detected post-2020 on satellite alert
    legalityVerified: false,
    tracesNtDdsReference: undefined,
    status: 'NON_COMPLIANT_BLOCKED',
    riskAssessment: 'HIGH',
    verifiedAt: '2026-09-18T11:45:00Z',
  },
];

// --- Generated Official Audit Packs ---
export const SEED_AUDIT_PACKS: GeneratedAuditPack[] = [
  {
    id: 'pack-2026-danone-01',
    referenceNumber: 'AUDIT-2026-CW-DAN-001',
    generatedAt: '2026-09-20T10:00:00Z',
    config: {
      reportTitle: 'Rapport Annuel de Conformité Chaîne d’Approvisionnement CSRD ESRS E4 & S2',
      fiscalYear: 'Exercice 2025/2026',
      periodStart: '2025-01-01',
      periodEnd: '2026-09-20',
      leadAuditor: 'Claire de Montmirail (Direction RSE)',
      auditBody: 'PwC ESG Assurance & Commissaires aux Comptes',
      tenantId: 'tenant-danone-global',
      includeCertificatesDetails: true,
      includeCryptoProofSeal: true,
      includeEudrAnnexes: true,
      includeCapaRemediation: true,
    },
    executiveSummary: {
      totalSuppliersAudited: 5,
      overallComplianceRate: 88,
      activeCertificatesCount: 14,
      expiredRevokedCount: 2,
      derogationsApprovedCount: 1,
      unresolvedCriticalAlertsCount: 1,
    },
    cryptoSeal: {
      blockNumber: 42,
      sealHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      previousHash: 'a718c392f1b0a7b451f28b71d99d1234567890abcdef1234567890abcdef1234',
      algorithm: 'SHA-256 (Chaîne d’audit certifiée)',
      verifiedIntegrity: true,
    },
    standardsSummary: [
      { standard: 'ECOCERT_BIO', validCount: 4, expiredCount: 0, coveragePercent: 100 },
      { standard: 'FSC', validCount: 3, expiredCount: 0, coveragePercent: 100 },
      { standard: 'FAIRTRADE', validCount: 2, expiredCount: 1, coveragePercent: 67 },
      { standard: 'GOTS', validCount: 1, expiredCount: 0, coveragePercent: 100 },
      { standard: 'OEKO_TEX_100', validCount: 1, expiredCount: 0, coveragePercent: 100 },
    ],
    eudrSummary: {
      totalPlotsDeclared: 5,
      gpsVerifiedRate: 80,
      eudrComplianceRate: 60,
      highRiskOriginsCount: 2,
    },
  },
];

