import {
  WebhookEndpoint,
  WebhookDeliveryLog,
  DeadLetterQueueItem,
  ApiDocEndpoint,
} from '../types/webhook';

export const SEED_WEBHOOK_ENDPOINTS: WebhookEndpoint[] = [
  {
    id: 'wh-sap-01',
    tenantId: 'tenant-danone-global',
    name: 'SAP S/4HANA Enterprise - Goods Receipt Gate (Entrepôt Rungis)',
    url: 'https://sap-gateway.danone.corp/api/v2/certiwatch/goods-receipt',
    secret: 'whsec_sap_998a4f10283bc91e7724a810b42c',
    events: ['CERTIFICATE_REVOKED', 'SUPPLIER_BLOCKED', 'EUDR_NON_COMPLIANT'],
    status: 'ACTIVE',
    failureCount: 0,
    lastSuccessAt: '2026-09-24T18:32:00Z',
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'wh-oracle-02',
    tenantId: 'tenant-danone-global',
    name: 'Oracle NetSuite ERP - Module Achats & Approbations PO',
    url: 'https://netsuite-connector.danone.corp/webhooks/po-validation',
    secret: 'whsec_net_441c882190ee012a9bc4128f7311',
    events: ['CERTIFICATE_EXPIRED', 'DEROGATION_EXPIRED', 'ORDER_CHECK_FAILED'],
    status: 'ACTIVE',
    failureCount: 1,
    lastSuccessAt: '2026-09-23T14:10:00Z',
    lastFailureAt: '2026-09-24T20:15:00Z',
    createdAt: '2026-02-01T11:30:00Z',
  },
  {
    id: 'wh-coupa-03',
    tenantId: 'tenant-danone-global',
    name: 'Coupa Procurement - API Middleware Supplier Master',
    url: 'https://coupa-middleware.danone.corp/api/supplier-status',
    secret: 'whsec_cou_7718aa0012bcfe891044bb78921a',
    events: ['CERTIFICATE_REVOKED', 'CERTIFICATE_RENEWED', 'SUPPLIER_UNBLOCKED'],
    status: 'ACTIVE',
    failureCount: 0,
    lastSuccessAt: '2026-09-25T08:12:00Z',
    createdAt: '2026-03-10T15:45:00Z',
  },
];

export const SEED_WEBHOOK_DELIVERIES: WebhookDeliveryLog[] = [
  {
    id: 'del-01',
    endpointId: 'wh-sap-01',
    endpointName: 'SAP S/4HANA Enterprise - Goods Receipt Gate',
    event: 'CERTIFICATE_REVOKED',
    payload: {
      event: 'CERTIFICATE_REVOKED',
      certificateNumber: 'CU-849301-GOTS-2024',
      standard: 'GOTS',
      supplierId: 'sup-danone-02',
      supplierName: 'Agrícola Andina del Cacao S.A.C.',
      reason: 'Audit de contrôle défavorable par Ecocert',
      erpBlockEnforced: true,
      timestamp: '2026-09-24T18:31:58Z',
    },
    signature: 'sha256=9a48f710b82ec45100c8f9411bb2c81e9447102e88a310bb4710cc4918e91024',
    statusCode: 200,
    durationMs: 48,
    timestamp: '2026-09-24T18:32:00Z',
    retryCount: 0,
    status: 'SUCCESS',
  },
  {
    id: 'del-02',
    endpointId: 'wh-coupa-03',
    endpointName: 'Coupa Procurement - API Middleware',
    event: 'CERTIFICATE_RENEWED',
    payload: {
      event: 'CERTIFICATE_RENEWED',
      certificateNumber: 'FSC-C012984-2026',
      standard: 'FSC',
      supplierId: 'sup-danone-03',
      supplierName: 'Cartonneries Européennes & Cellulose SA',
      validUntil: '2027-09-30',
      status: 'VALID',
    },
    signature: 'sha256=12ab78ef459900cde104781299bbecfa10984577884102ef891044bb78921a44',
    statusCode: 200,
    durationMs: 72,
    timestamp: '2026-09-25T08:12:00Z',
    retryCount: 0,
    status: 'SUCCESS',
  },
  {
    id: 'del-03',
    endpointId: 'wh-oracle-02',
    endpointName: 'Oracle NetSuite ERP - Module Achats',
    event: 'ORDER_CHECK_FAILED',
    payload: {
      event: 'ORDER_CHECK_FAILED',
      poNumber: 'PO-2026-DAN-8812',
      supplierId: 'sup-danone-05',
      supplierName: 'Sucreries & Distilleries Réunionnaises Bio',
      reasons: ['Alerte déforestation EUDR post-2020 active'],
      verdict: 'BLOCKED',
    },
    signature: 'sha256=fe891024ac88910bc457712398fa8811776510449900ee123488771122aabb55',
    statusCode: 504,
    durationMs: 5021,
    timestamp: '2026-09-24T20:15:00Z',
    retryCount: 2,
    status: 'FAILED',
    errorMessage: 'Gateway Timeout (NetSuite Endpoint uncontactable after 5000ms)',
  },
];

export const SEED_DLQ_ITEMS: DeadLetterQueueItem[] = [
  {
    id: 'dlq-item-01',
    webhookId: 'wh-oracle-02',
    webhookName: 'Oracle NetSuite ERP - Module Achats & Approbations PO',
    targetUrl: 'https://netsuite-connector.danone.corp/webhooks/po-validation',
    event: 'ORDER_CHECK_FAILED',
    attemptCount: 3,
    maxAttempts: 5,
    firstFailedAt: '2026-09-24T20:10:00Z',
    lastFailedAt: '2026-09-24T20:15:00Z',
    nextRetryAt: '2026-09-25T11:00:00Z',
    payload: {
      event: 'ORDER_CHECK_FAILED',
      poNumber: 'PO-2026-DAN-8812',
      supplierId: 'sup-danone-05',
      supplierName: 'Sucreries & Distilleries Réunionnaises Bio',
      reasons: ['Alerte déforestation EUDR post-2020 active'],
      verdict: 'BLOCKED',
    },
    lastError: 'HTTP 504 Gateway Timeout: Target server did not respond in 5000ms',
    status: 'PENDING_RETRY',
  },
  {
    id: 'dlq-item-02',
    webhookId: 'wh-sap-01',
    webhookName: 'SAP S/4HANA Enterprise - Goods Receipt Gate',
    targetUrl: 'https://sap-gateway.danone.corp/api/v2/certiwatch/goods-receipt',
    event: 'EUDR_NON_COMPLIANT',
    attemptCount: 5,
    maxAttempts: 5,
    firstFailedAt: '2026-09-23T11:00:00Z',
    lastFailedAt: '2026-09-23T11:45:00Z',
    payload: {
      event: 'EUDR_NON_COMPLIANT',
      supplierId: 'sup-danone-05',
      parcelRef: 'BRA-MT-SOR-2025-EXT-99C',
      reason: 'Deforestation detected post-Dec 2020 via Sentinel-2 satellite',
    },
    lastError: 'HTTP 429 Too Many Requests: Rate limit exceeded on SAP ingestion proxy',
    status: 'PENDING_RETRY',
  },
];

export const SEED_API_DOCUMENTATION: ApiDocEndpoint[] = [
  {
    method: 'POST',
    path: '/api/v1/erp/check-po',
    category: 'ERP Orders',
    summary: 'Vérification de conformité avant émission d’un bon de commande ERP',
    description:
      'Interrogé en temps réel par SAP S/4HANA, Coupa ou NetSuite avant la validation définitive d’un bon d’achat (Purchase Order). Renvoie ALLOWED si les certificats exigés sont valides, ou BLOCKED avec le détail des motifs.',
    headers: {
      Authorization: 'Bearer cw_live_api_key_...',
      'Content-Type': 'application/json',
    },
    requestBody: {
      supplierId: 'sup-danone-02',
      productCategory: 'Cacao & Dérivés',
      orderAmountEur: 125000,
      deliveryCountry: 'FR',
      poNumber: 'PO-2026-SAP-99120',
    },
    responseSample: {
      decision: 'ALLOWED',
      status: 200,
      supplierId: 'sup-danone-02',
      supplierName: 'Agrícola Andina del Cacao S.A.C.',
      verifiedCertificates: [
        { standard: 'FAIRTRADE', certNumber: 'FLO-ID-44102', status: 'VALID', validUntil: '2026-11-30' },
      ],
      missingStandards: [],
      erpBlockEnforced: false,
      timestamp: '2026-09-25T10:18:00Z',
      digitalSeal: 'sha256=88a104f2...',
    },
  },
  {
    method: 'GET',
    path: '/api/v1/suppliers/{id}/compliance-status',
    category: 'Suppliers',
    summary: 'Statut de conformité 360° et score de risque d’un tiers',
    description:
      'Renvoie la synthèse instantanée du statut du tiers : score de risque multi-facteurs, état des certificats, blocage ERP en vigueur et conformité EUDR.',
    headers: {
      Authorization: 'Bearer cw_live_api_key_...',
    },
    queryParams: {
      includeCertificates: 'true',
      includeEudrPlots: 'true',
    },
    responseSample: {
      supplierId: 'sup-danone-01',
      legalName: 'BioLait Normandie SAS',
      siret: 'FR 849 201 394 00012',
      riskLevel: 'LOW',
      multiFactorRiskScore: 12,
      erpBlockStatus: 'ALLOWED',
      activeCertificatesCount: 2,
      eudrComplianceRate: 100,
      lastAuditVerification: '2026-09-24T08:00:00Z',
    },
  },
  {
    method: 'POST',
    path: '/api/v1/certificates/verify',
    category: 'Certificates',
    summary: 'Déclenchement d’une vérification officielle de certificat en temps réel',
    description:
      'Interroge directement l’API du registre officiel émetteur (Ecocert, FSC, GOTS, OEKO-TEX, Fairtrade) avec comparaison OCR et détection d’anomalies.',
    headers: {
      Authorization: 'Bearer cw_live_api_key_...',
      'Content-Type': 'application/json',
    },
    requestBody: {
      standard: 'FSC',
      certificateNumber: 'FSC-C012984-2026',
      holderName: 'Cartonneries Européennes & Cellulose SA',
    },
    responseSample: {
      outcome: 'MATCH',
      officialStatus: 'VALID',
      verifiedAgainstProvider: 'FSC Public Search Registry API v2',
      holderMatched: true,
      officialExpiryDate: '2027-09-30',
      anomaliesDetected: [],
      timestamp: '2026-09-25T10:18:22Z',
    },
  },
  {
    method: 'GET',
    path: '/api/v1/eudr/plots',
    category: 'EUDR',
    summary: 'Extraction des parcelles géolocalisées et références TRACES-NT',
    description:
      'Permet aux systèmes logistiques et transitaires en douane de récupérer les coordonnées GPS décimales (polygones WGS84) et les numéros DDS pour le dédouanement.',
    headers: {
      Authorization: 'Bearer cw_live_api_key_...',
    },
    queryParams: {
      commodity: 'COCOA',
      status: 'COMPLIANT',
    },
    responseSample: {
      totalPlots: 1,
      plots: [
        {
          id: 'eudr-plot-01',
          supplierName: 'Agrícola Andina del Cacao S.A.C.',
          commodity: 'COCOA',
          countryOfProduction: 'Pérou (San Martín / Tocache)',
          plotReference: 'PER-SM-TOC-2024-LOT-44B',
          gpsPolygonOrPoint: '-8.18721, -76.51442 (Polygone 14.8 ha)',
          deforestationCutoffDateMet: true,
          tracesNtDdsReference: 'DDS-EUDR-2026-PE-098842',
          status: 'COMPLIANT',
        },
      ],
    },
  },
];
